Verifying JWT options
uport-project/kotlin-did-jwt pull request #2
Opened 2019-05-13 16:33 UTC by ugoamanoh

#### What's Here
Replicating the JS implementation for verifying the audience when verifying a JWT token. If the payload contains an audience then the user is expected to pass in an audience or the method throws an `InvalidJWTException`. Checks are done to verify if the correct is being used and any failures cause an `InvalidJWTException`. 

According to the specs
```
The DID or URL of the audience of the JWT. Our libraries or app will not accept any JWT that has someone else as the audience
```

#### Testing
Run gradle command `./gradlew test cC --no-parallel`

2019-05-13 16:43 UTC, mirceanis requested changes
looks good, there are some minor nits to fix.
It is also recommended to run a code reformat (select project and CMD+ALT+L)

2019-05-13 16:43 UTC, mirceanis commented on jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
> +                if (!aud.equals(payload.aud)) {
please use `!=` instead of `!equals`
on kotlin it compares contents, not references
```suggestion
                if (aud != payload.aud) {
```

2019-05-13 16:43 UTC, mirceanis commented on jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
> +                    throw InvalidJWTException("JWT audience does not match your DID: aud: ${payload.aud} !== yours: ${aud}")
```suggestion
                    throw InvalidJWTException("JWT audience does not match your DID: aud: ${payload.aud} != yours: ${aud}")
```

2019-05-13 16:43 UTC, mirceanis commented on jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
> +                if (!callbackUrl.equals(payload.aud)) {
```suggestion
                if (callbackUrl != payload.aud) {
```

2019-05-13 16:43 UTC, mirceanis commented on jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
> +                    throw InvalidJWTException("JWT audience does not match the callback url: aud: ${payload.aud} !== url: ${callbackUrl}")
```suggestion
                    throw InvalidJWTException("JWT audience does not match the callback url: aud: ${payload.aud} != url: ${callbackUrl}")
```

2019-05-13 17:28 UTC, ugoamanoh commented on jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
> +                    throw InvalidJWTException("JWT audience does not match your DID: aud: ${payload.aud} !== yours: ${aud}")
@mirceanis done, please re-check

2019-05-13 19:49 UTC, mirceanis approved these changes
Looks good.
There's one thing I missed initially, there is no normalization of the DID before comparison.
This needs to be specified in docs.

2019-05-16 11:54 UTC, ugoamanoh commented
@mirceanis please review

2019-05-17 10:22 UTC, mirceanis approved these changes

2019-05-17 10:22 UTC, mirceanis commented on jwt/src/main/java/me/uport/sdk/jwt/jwtUtils.kt
> +
```suggestion
  if (did.startsWith("did:")) {
    return did
  }
```

2019-05-17 10:23 UTC, merged